config/routes.rb
Rails.application.routes.draw do
  get 'posts/index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  get '/about' => "home#about"
  get '/contact' => "home#contact"

  get '/users' => "users#index"
  get '/users/edit', to: "users#edit"
  get '/users/:id' => "users#show", as: :user
  post '/users' => "users#create"
  patch 'users/:id', to: 'users#update'
  delete 'users/:id', to: 'users#destroy'

  get '/search' => 'users#search'

  resources :posts, :comments

  root 'users#new'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :user?

  def index
    @posts = Post.all
  end

  def new

  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comments = @post.comments
    @toplevels = get_top_level_comments(@post)
    @comment = Comment.new


  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    puts "********** PARAMS ****************"
    puts params
    puts "******** ID? *******"
    puts params[:post][:body]
    puts params[:id]

    post_id = params[:id]
    @post = Post.find(post_id)
    @user = @post.user
    body = params[:post][:body]
    @post.update(body: body)
    redirect_to user_path @user
    # redirect_to post_path post_id
  end

  def create
    puts "******************* PARAMS ********************"
    puts params
    body = params[:post][:body]
    id = current_user.id
    @post = Post.new(user_id: id, body: body)
    # @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "Your post was created successfully."
      redirect_to user_path current_user
    else
      flash[:alert] = "There was a problem. Please try again"
      redirect_to user_path current_user
    end
  end

  def destroy
    puts "*" * 25
    puts params
    @post = Post.find(params[:id])
    @user = @post.user
    if @post.destroy
      flash[:notice] = "Post has been deleted."
      redirect_to user_path @user
    else
      flash[:alert] = "There was a problem."
      redirect_to post_path @post
    end
  end

  def print_child_and_children(comment)
      puts comment.body
      children = comment.children
      children.each do |child|
        print_child_and_children(child)
      end
  end

  private

  def post_params
    params.require(:post).permit(:body, :user_id)
  end

  def print_child_and_children(comment)
      puts comment.body
      children = comment.children
      children.each do |child|
        print_child_and_children(child)
      end
  end

  def get_top_level_comments(post)
    Comment.where(post_id: post.id, parent_id: nil)
  end

  def user?
    unless current_user
      flash[:alert] = "You must be logged in."
      redirect_to root_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  # def print_child_and_children(comment)
  #     puts comment.body
  #     children = comment.children
  #     children.each do |child|
  #       print_child_and_children(child)
  #     end
  # end

end

app/views/posts/edit.html.erb
<div class="header">
  <h1> Post #<%= @post.id %> </h1>

  <%= form_for @post do |f| %>
    <%= f.label "Edit your post" %>
    <br>
    <%= f.text_area :body, class: "new-post" %>
    <br>


    <%=f.submit :Update %>
  <% end %>

</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    <h1 class="posts-header">Posts</h1>
    <br>

    <ul>
      <% @posts.reverse.each do |post| %>
      <li>
        <%= post.user.fname + " " + post.user.lname + " said:" %>
        <br>
        <a href="posts/<%=post.id%>">
          <%= truncate post.body, length: 200 %>
        </a>
        <br>
        <%= post.created_at.strftime("%B %d, %Y at %I:%M %p") %>
      </li>
      <br>
      <% end %>

    </ul>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <div class="col-sm-8 col-sm-offset-2">
    <h1>Post #<%=@post.id%></h1>

    <h4>
      <%= @post.user.fname + " " + @post.user.lname %>
    </h4>
    <p>
       <%=@post.created_at.strftime("%B %d, %Y at %I:%M %p")  %>
    </p>
    <h4>
      <%= simple_format @post.body %>
    </h4>

    <% if @user == current_user %>
      <a href="<%=@post.id%>/edit">Edit Post</a>
      <%= link_to("Delete Post", post_path(@post.id), method: :delete)%>
    <% elsif current_user %>
      <%= link_to "Comment", new_comment_path(:post_id => params[:id]) %>
    <% else %>
      <a href="/login">Login to comment</a>

    <% end %>
  </div>

</div>



<br>
<div class="row">
  <div class="col-sm-10 col-sm-offset-2">
    <h4>Comments</h4>
    <% if @comments.length == 0 %>
    <p>
      <em>There are no comments for this post.</em>
    </p>
    <% end %>

    <% @toplevels.each do |toplevel| %>

    <% def print_child_and_children(comment) %>
    <br>
      <ul>
        <li>
          <%= comment.body %>
          <br>
          <p>
            - <%= comment.user.fname + " " + comment.user.lname + ", " + comment.created_at.strftime("%B %d, %Y at %I:%M %p") %>
          </p>
          <% if comment.user == current_user %>
            <a href="../comments/<%=comment.id%>/edit">Edit</a>
            <%= link_to("Delete", comment_path(comment.id), method: :delete)%>
            <br>
          <% elsif current_user %>
            <a class="reply">Reply</a>

          <% end %>
          <%= form_for @comment, url: comments_path, :html => {class: "dropdown-reply"} do |f| %>
            <br>
            <%= f.text_area :body %>
            <br>
            <%=f.submit :Reply %>

            <%=f.hidden_field :post_id, :value => @post.id %>
            <%= f.hidden_field :parent_id, :value => comment.id %>
          <% end %>
        </li>
        <% children = comment.children
           children.each do |child|
             print_child_and_children(child) %>
        <% end %>
      </ul>
    <% end %>

    <% print_child_and_children(toplevel) %>

    <% end %>


  </div>

</div>



<!-- def print_children(comment)
  if comment.children.first == nil
    puts comment.body
  else
    children = comment.children
    children.each do |child|
      puts child.body
      print_children(child)
    end
  end
end

def print_children(comment)
    puts comment
    children = comment.children
    children.each do |child|
      print_children(child)
    end
end -->